##**THEORETICAL QUESTION**


##Q1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python’s capabilities for numerical operations?



##Ans-NumPy (Numerical Python) is a powerful library in Python used for numerical computations. It provides support for large, multi-dimensional arrays and matrices along with a rich collection of mathematical functions to operate on these arrays. The key advantages of NumPy include:




##1.   **Speed and Performance:** Operations in NumPy are implemented in C, which makes them faster than native Python lists.

##2.   **Memory Efficiency:** NumPy arrays consume less memory as they are densely packed with data of the same type.

##3.   **bold text**Convenient Mathematical Functions: Functions like linear algebra, Fourier transforms, and statistics are built-in.

##4.   **Broadcasting and Vectorization:** NumPy enables element-wise operations without using explicit loops, which improves code efficiency and readability.


##These features make NumPy ideal for scientific computing, data analysis, machine learning, and more.





##Q2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?




##Ans-Both **np.mean()** and **np.average()** are used to calculate the average of elements in an array, but they differ slightly:

##1.   **np.mean()** calculates the arithmetic mean and treats all elements equally.


##2.   **np.average()** allows assigning weights to elements, making it suitable for calculating weighted averages.



##Use **np.mean()** when all elements contribute equally to the mean.

##Use **np.average()** when certain elements have more significance and should be given higher weights.



##**Example:**




In [1]:
import numpy as np
a = np.array([1, 2, 3])
print(np.mean(a))         # Output: 2.0
print(np.average(a, weights=[1, 1, 2]))  # Output: 2.25


2.0
2.25


##Q3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.





##Ans-To reverse NumPy arrays, slicing or specific functions can be used:




##1.   **1D Array:** Use slicing [::-1] to reverse the elements.


##2.   **2D Array:** Reverse rows or columns using slicing along specific axes.


##**Example:**



In [2]:
import numpy as np

# 1D Array
arr1d = np.array([1, 2, 3, 4])
print(arr1d[::-1])  # Output: [4 3 2 1]

# 2D Array
arr2d = np.array([[1, 2], [3, 4]])

# Reverse rows
print(arr2d[::-1])
# Output:
# [[3 4]
#  [1 2]]

# Reverse columns
print(arr2d[:, ::-1])
# Output:
# [[2 1]
#  [4 3]]


[4 3 2 1]
[[3 4]
 [1 2]]
[[2 1]
 [4 3]]


##Q4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.




##Ans- WE can determine the data type of a NumPy array using the **.dtype** attribute:

In [3]:
arr = np.array([1, 2, 3])
print(arr.dtype)  # Output: int64 (or similar depending on system)


int64


##**Q4 Continue....**


##**Importance of Data Types:**





##1.   Choosing appropriate data types helps minimize memory usage.

##2.   Fixed-type arrays (unlike Python lists) allow faster computation.

##3.   Specific types (e.g., float32 vs float64) can optimize performance in large datasets.


##Efficient data type selection leads to better performance and scalability in data-intensive applications.




##Q5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python




##Ans- In NumPy, an **ndarray** is a multi-dimensional, homogeneous array object that forms the core of the library. Unlike standard Python lists that can hold elements of varying types, ndarrays store items of the same type, which enables fast mathematical and logical operations. They support vectorized operations, broadcasting, and a wide variety of mathematical functions, making them suitable for high-performance tasks. The uniformity and efficiency of ndarrays significantly enhance speed and reduce memory usage, making them more powerful than Python lists for numerical and scientific computations.



##**Example:**

In [4]:
import numpy as np
arr = np.array([1, 2, 3])
print(arr * 2)  # Output: [2 4 6]

lst = [1, 2, 3]
print([x * 2 for x in lst])  # Output: [2, 4, 6]


[2 4 6]
[2, 4, 6]


##Q6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.




##Ans-NumPy arrays outperform Python lists due to:



##1.   Vectorization: Element-wise operations are performed without explicit loops.


##2.   Contiguous Memory Allocation: Enhances CPU cache efficiency.

##3.   Compiled Backend: Operations are implemented in optimized C code.


##**Benchmark Example:**



In [5]:
import numpy as np
import time

a = list(range(1000000))
b = np.array(a)

# Python list
start = time.time()
a = [x * 2 for x in a]
print("List time:", time.time() - start)

# NumPy array
start = time.time()
b = b * 2
print("NumPy time:", time.time() - start)


List time: 0.12122058868408203
NumPy time: 0.004073143005371094


##Q7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.




##Ans-The **vstack()** and **hstack()** functions in NumPy are used to stack arrays vertically and horizontally, respectively. **vstack()** adds new rows by stacking arrays on top of one another, while **hstack()** appends arrays side by side by adding new columns. These functions are helpful in combining datasets, reshaping matrices, and constructing larger arrays from smaller components. For example, stacking **[1, 2]** and **[3, 4]** using **vstack()** results in a 2x2 matrix, whereas using **hstack()** produces a single row with four elements. These operations are essential in data transformation and matrix manipulation.


##**Example:**

In [6]:
import numpy as np
a = np.array([1, 2])
b = np.array([3, 4])

# Vertical stack
print(np.vstack((a, b)))
# Output:
# [[1 2]
#  [3 4]]

# Horizontal stack
print(np.hstack((a, b)))
# Output: [1 2 3 4]


[[1 2]
 [3 4]]
[1 2 3 4]


##Q8. Explain the differences between flip() and fliplr() methods in NumPy, including their effects on various array dimensions.




##Ans-The **flip()** and **fliplr()** functions in NumPy both reverse elements in an array, but they differ in application. **flip()** can reverse elements along any specified axis, or all axes if no axis is mentioned, making it versatile for various array types. On the other hand, **fliplr()** is specifically designed for 2D arrays and flips the elements from left to right, i.e., it reverses the order of columns. These functions are useful in image processing, data augmentation, and matrix manipulation tasks where directional reversal is required.


##**Example:**

In [7]:
arr = np.array([[1, 2], [3, 4]])

print(np.flip(arr))
# Output: [[4 3]
#          [2 1]]

print(np.fliplr(arr))
# Output: [[2 1]
#          [4 3]]


[[4 3]
 [2 1]]
[[2 1]
 [4 3]]


##Q9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?





##Ans-**np.array_split()** divides an array into sub-arrays. Unlike **np.split()**, it can handle cases where the array does not divide evenly.



##**Example:**

In [8]:
arr = np.array([1, 2, 3, 4, 5])
print(np.array_split(arr, 3))
# Output: [array([1, 2]), array([3, 4]), array([5])]


[array([1, 2]), array([3, 4]), array([5])]


##Q10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?



##Ans- Vectorization and broadcasting are two powerful concepts in NumPy that greatly enhance computational efficiency. Vectorization refers to the process of applying operations to entire arrays rather than individual elements, which eliminates the need for loops and results in faster execution. Broadcasting allows arrays of different shapes to be combined in operations by automatically expanding one of the arrays to match the shape of the other. Together, these features simplify code and boost performance, making NumPy highly effective for numerical computations and large-scale data processing tasks.




##**Example:**

In [9]:
import numpy as np
a = np.array([1, 2, 3])
b = 2
print(a * b)  # Broadcasting scalar across array


[2 4 6]


##**PRACTICAL QUESTION**

#Q1.Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [ ]:
import numpy as np

arr1 = np.random.randint(1, 101, (3, 3))
transposed_arr1 = arr1.T
print("Original:\n", arr1)
print("Transposed:\n", transposed_arr1)


Original:
 [[14  9 35]
 [46 26 16]
 [ 8 12 62]]
Transposed:
 [[14 46  8]
 [ 9 26 12]
 [35 16 62]]


#Q2.Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [ ]:
arr2 = np.arange(10)
reshaped_2x5 = arr2.reshape(2, 5)
reshaped_5x2 = reshaped_2x5.reshape(5, 2)
print("5x2 reshaped:\n", reshaped_5x2)


5x2 reshaped:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


#Q3.Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [ ]:
arr3 = np.random.rand(4, 4)
arr3_with_border = np.pad(arr3, pad_width=1, mode='constant', constant_values=0)
print("With border:\n", arr3_with_border)


With border:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.22418586 0.25323251 0.32084247 0.43961841 0.        ]
 [0.         0.40438298 0.88392448 0.08699336 0.46985082 0.        ]
 [0.         0.31035677 0.83396844 0.60999253 0.71835327 0.        ]
 [0.         0.79023027 0.01872053 0.5919136  0.33278947 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


#Q4.Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [ ]:
arr4 = np.arange(10, 61, 5)
print(arr4)


[10 15 20 25 30 35 40 45 50 55 60]


#Q5.Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

In [ ]:
arr5 = np.array(['python', 'numpy', 'pandas'])
print("Uppercase:", np.char.upper(arr5))
print("Lowercase:", np.char.lower(arr5))
print("Title Case:", np.char.title(arr5))


Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Title Case: ['Python' 'Numpy' 'Pandas']


#Q6.Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [ ]:
arr6 = np.array(['data', 'science', 'numpy'])
spaced = np.char.join(' ', arr6)
print(spaced)


['d a t a' 's c i e n c e' 'n u m p y']


#Q7.Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [ ]:
a = np.random.randint(1, 10, (3, 3))
b = np.random.randint(1, 10, (3, 3))

print("Addition:\n", a + b)
print("Subtraction:\n", a - b)
print("Multiplication:\n", a * b)
print("Division:\n", a / b)


Addition:
 [[ 9  8 11]
 [13  6 15]
 [13 12  9]]
Subtraction:
 [[-5  0 -5]
 [-1 -4 -1]
 [ 3  6 -5]]
Multiplication:
 [[14 16 24]
 [42  5 56]
 [40 27 14]]
Division:
 [[0.28571429 1.         0.375     ]
 [0.85714286 0.2        0.875     ]
 [1.6        3.         0.28571429]]


#Q8.Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [ ]:
identity = np.eye(5)
diagonal = np.diag(identity)
print("Diagonal elements:", diagonal)


Diagonal elements: [1. 1. 1. 1. 1.]


#Q9.Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

In [ ]:
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

arr9 = np.random.randint(0, 1000, 100)
primes = np.array([x for x in arr9 if is_prime(x)])
print("Prime numbers:\n", primes)


Prime numbers:
 [757 317   2 457 557 929 857 457 853 211 971 557 853   5  73 619 541  41
 883 601]


#Q10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [ ]:
temps = np.random.uniform(15, 35, 28)  # daily temps for a month, adjusted to 28 days
weekly_avg = temps.reshape(4, 7).mean(axis=1)  # Reshape to 4 weeks and calculate weekly averages
print("Weekly averages:", weekly_avg)

Weekly averages: [23.00150513 28.0077057  22.87252872 25.2730223 ]
